# See https://docs.sourcegraph.com/dev/background-information/ci#pr-auditor
name: pr-auditor
on:
  pull_request:
    types: [closed, edited, opened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  check-pr:
    uses: sourcegraph/devx-service/.github/workflows/pr-auditor.yml@jsm/pr-auditor
    secrets: inherit
    with:
      skip-status: true
      issues-repo-name: rfc-912-playground
      issues-repo-owner: jamesmcnamara
